a = float(input("Enter the length : "))
print(f"perimeter of circle : {2 * 3.14 * a}")
print(f"area of circle : {3.14 * a * a}")
print(f"perimeter of the triangle : {3 * a}")
print(f"area of triangle : {(1.73/4) * a*a}")
